In [3]:
import numpy as no

## Operations on sets

In [6]:
set1 = {'a',1,3,4}
set2 = {1,3,4}

In [7]:
a = no.array(set1)
b = no.array(set2)

In [9]:
set1 - set2 # sets can be subtracted

{'a'}

In [22]:
set2 + set2 # sets can't be added

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [49]:
set1.union(set2) # seta.union(setb,setc....) gives the union of all the sets. 

{1, 3, 4, 'a'}

In [50]:
set1 | set2 # This gives union as well.

{1, 3, 4, 'a'}

In [53]:
set1.intersection(set2) # seta.intersection(setb,setc....) gives the interstection of all the sets. 

{1, 3, 4}

In [54]:
set1 & set2 # This gives intersection as well.

{1, 3, 4}

In [10]:
a - b # arrays of sets can be subtracted

{'a'}

In [51]:
a | b

{1, 3, 4, 'a'}

## Operations on lists

In [38]:
list1 = [1,3,4]
list2 = [1,3,'a',6]

In [39]:
list1 + list2 # lists when added yield catenation and can't be subtracted

[1, 3, 4, 1, 3, 'a', 6]

In [59]:
[1,2,3]*[4,5,6] # lists can't be multiplied.

TypeError: can't multiply sequence by non-int of type 'list'

In [45]:
c = no.array([1,2,3])
d = no.array([1,2,3])

In [46]:
c - d  # arrays made of similar lists can be subtracted.

array([0, 0, 0])

In [55]:
c + d # arrays made of similar lists can be added

array([2, 4, 6])

In [56]:
c*d # arrays of lists cant be multiplied to multiply corresponding values.

array([1, 4, 9])

In [61]:
listoflists1 = [[1,2],[2,3]]
listoflists2 = [[1,2],[2,3]]
no.array(listoflists1)*no.array(listoflists2)

array([[1, 4],
       [4, 9]])

## Random

In [1]:
import numpy as np

In [11]:
np.random.randint([1,2,3],4) # prodces a 3x1 array with different min values but same maximum value

array([3, 2, 3])

In [16]:
np.random.randint(2,[4,5,3]) # prodces a 3x1 array with different max values but same min value

array([3, 2, 2])

In [12]:
np.random.randint([1,2,3],[4,5,6]) # prodces a 3x1 array with different min values and max values

array([3, 4, 5])

In [17]:
np.random.randint(1,3,size = (3,4))

array([[2, 1, 1, 2],
       [1, 2, 1, 1],
       [2, 2, 1, 2]])

## Pandas

In [19]:
import pandas as pd

In [20]:
pd.Series("Hello Hi Hey bro".split(), "1 2 3 4 ".split())

1    Hello
2       Hi
3      Hey
4      bro
dtype: object