## Numpy 

In [63]:
import numpy as np

### 1 Dimensional arrays:

#### Initialisation of arrays:

In [64]:
s_list = [1,2,3]

In [65]:
arr = np.array(s_list)
np.array(s_list)  # initialisation by name

array([1, 2, 3])

In [66]:
np.array([1,'a','c']) # initialisation by data

array(['1', 'a', 'c'], dtype='<U11')

Arrays can be made of lists and tuples as well, but they behave in their own way. For instance, arrays made of sets can't be added.

#### Forming 1 dimensional arrays

In [67]:
np.arange(5,30,6) # (initial value, final value less than , step)

array([ 5, 11, 17, 23, 29])

In [68]:
np.arange(5,30) # default step = 1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
np.arange(30) # default intial value = 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [70]:
np.linspace(5,30,5) # (inital value, final value, no. of total values)

array([ 5.  , 11.25, 17.5 , 23.75, 30.  ])

In [71]:
np.linspace(5,30,5, dtype = int)

array([ 5, 11, 17, 23, 30])

In [72]:
np.linspace(20,1) # 50 values by default.

array([20.        , 19.6122449 , 19.2244898 , 18.83673469, 18.44897959,
       18.06122449, 17.67346939, 17.28571429, 16.89795918, 16.51020408,
       16.12244898, 15.73469388, 15.34693878, 14.95918367, 14.57142857,
       14.18367347, 13.79591837, 13.40816327, 13.02040816, 12.63265306,
       12.24489796, 11.85714286, 11.46938776, 11.08163265, 10.69387755,
       10.30612245,  9.91836735,  9.53061224,  9.14285714,  8.75510204,
        8.36734694,  7.97959184,  7.59183673,  7.20408163,  6.81632653,
        6.42857143,  6.04081633,  5.65306122,  5.26530612,  4.87755102,
        4.48979592,  4.10204082,  3.71428571,  3.32653061,  2.93877551,
        2.55102041,  2.16326531,  1.7755102 ,  1.3877551 ,  1.        ])

In [73]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [74]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [75]:
np.zeros(7,int)

array([0, 0, 0, 0, 0, 0, 0])

In [76]:
np.eye(1) # identity matrix (makes more sense for higher orders.)

array([[1.]])

#### Working with one dimensional arrays

In [77]:
np.mean(arr)

2.0

In [78]:
np.median(arr) # There's no mode with np, I checked.

2.0

In [79]:
np.var(arr)

0.6666666666666666

In [80]:
np.std(arr)

0.816496580927726

In [81]:
np.square(arr)

array([1, 4, 9], dtype=int32)

In [82]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081])

In [83]:
np.min(arr) # same goes for max

1

In [84]:
np.argmin(arr) # arg of min value # same goes for max.

0

In [85]:
e = np.exp(arr)
e

array([ 2.71828183,  7.3890561 , 20.08553692])

In [86]:
np.round(e,3) # rounds off upto 3 decimal places.

array([ 2.718,  7.389, 20.086])

The above commands can be used for any kind of containers (list,tupple... ), not just arrays.

In [87]:
s_list2 = [3,4,5]
arr2 = np.array(s_list2)

In [88]:
s_list + s_list2 # when lists are added

[1, 2, 3, 3, 4, 5]

In [89]:
arr + arr2 # when arrays are added

array([4, 6, 8])

In [90]:
arr + 10 # or *10, /10, - 10

array([11, 12, 13])

In [91]:
arr < 2 # gives a boolean array of requried condition

array([ True, False, False])

In [92]:
b = np.array(["animals","a","b","animals"]) 

In [93]:
np.unique(b) # only retains unique elements.

array(['a', 'animals', 'b'], dtype='<U7')

In [94]:
arr[0:2] # slicing of array

array([1, 2])

In [95]:
arr[:] = 100 # arr[:] means all the values in arr, and when arr[:] = 100, all values will be set to 100
arr

array([100, 100, 100])

In [96]:
test = np.arange(12) # We'll use this later.

### 2 Dimensional arrays

#### Initialisation of arrays:

In [97]:
list_of_lists = [[1,2,3],[4,5,6]]

In [98]:
np.array(list_of_lists) # initialisation by name

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.array(([1,2,3],[4,'1','c'])) # initialisation by data. # notice that the lists went into (()) and not ()

array([['1', '2', '3'],
       ['4', '1', 'c']], dtype='<U11')

#### Forming 2 Dimensional Arrays

In [100]:
test = test.reshape(3,4) # Told you we'll use it. # Used to change the dimension of array, as long as the number of terms are same.
test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [103]:
np.eye(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

####  Random

In [104]:
np.random.randint(5,20,6) # gives 6 random integers between 5 and 20

array([15, 13, 13,  5,  5, 19])

In [105]:
np.random.randint(5,20,(3,5)) # gives (3,5) random integers between 5 and 20

array([[19, 17, 19, 18,  6],
       [ 6, 19,  7, 18, 18],
       [ 8,  5, 15,  9, 16]])

In [106]:
np.random.rand(3) # 3 random floating point numbers

array([0.22717762, 0.42129474, 0.29644839])

In [107]:
np.random.rand(3,3,4) # 3 sets of floating point numbers of the form (3,4)

array([[[0.34823488, 0.38755133, 0.17099846, 0.17236837],
        [0.60919636, 0.11952399, 0.0512708 , 0.31441947],
        [0.1990066 , 0.97881257, 0.9298638 , 0.51707034]],

       [[0.58215773, 0.39334555, 0.84803157, 0.47945123],
        [0.01115889, 0.06279005, 0.35745031, 0.05645516],
        [0.56208123, 0.3798675 , 0.1317949 , 0.70493065]],

       [[0.99064558, 0.87609801, 0.11202042, 0.92824007],
        [0.22965346, 0.97047124, 0.9368167 , 0.23269548],
        [0.39681881, 0.94958737, 0.41054043, 0.68689156]]])

In [108]:
np.random.rand(3,4)

array([[0.67059469, 0.33008073, 0.18555247, 0.30268374],
       [0.01053149, 0.26589713, 0.15667795, 0.33740495],
       [0.26211806, 0.43857759, 0.85771237, 0.72519239]])

In [109]:
np.random.randn(2,3) # samples of normal distribution with mean 0 and variance 1

array([[-0.70248921, -0.09023764,  0.50763283],
       [ 0.3943406 ,  0.03199455, -1.18977738]])

In [110]:
 np.random.normal(17,10,(2,3)) # samples of normal distribution with centre 17 and spread 17

array([[ 5.82715175, 19.09469382, 22.84347046],
       [17.26449485, 10.15940289, 28.76786552]])

#### Working with 2 dimensional arrays

In [111]:
test.shape # shape of the array

(3, 4)

In [112]:
test[2][3] # getting the value with indices

11

In [113]:
test[2,3] # getting the value with indices

11

In [114]:
test[1:3] # getting the rows with index

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
test[:,3] # all rows but column 3

array([ 3,  7, 11])

In [116]:
test[1,:] # all columns by row 1

array([4, 5, 6, 7])

In [117]:
test[:,(3,2)] # all rows but columns 3 and 2 in that order

array([[ 3,  2],
       [ 7,  6],
       [11, 10]])

In [118]:
test.T # transpose matrix

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])